baseURL = "https://forfuncsake.github.io/"
languageCode = "en-us"
title = "for func() sake { }"
theme = "hugo-theme-bootstrap4-blog"

# number of posts to show on home/category/tag pages (Default: 10)
paginate = 5


[permalinks]
  post = "/:year/:month/:title/"
  page = "/:slug/"

  [[menu.sidebar]]
    name = "Twitter"
    url = "https://twitter.com/forfuncsake"

  [[menu.sidebar]]
    name = "GitHub"
    url = "https://github.com/forfuncsake"

# Theme variables
# from: https://github.com/alanorth/hugo-theme-bootstrap4-blog/blob/master/exampleSite/config.toml
[params]
  # Site author
  author = "Dave Russell"
  disqusShortname = "forfuncsake"

  # Description/subtitle for homepage (can be Markdown)
  description = "Yet another gopher..."

  # Format dates with Go's time formatting
  date_format = "Mon Jan 02, 2006"

  # customise the contents of the navbar at the top of the page.  The default
  # behaviour is to list all static pages not in the posts directory. When the
  # parameter below is set to true you will have to manually add entries to the
  # navbar, either by adding the following menu variable to the front matter of
  # the relevant pages
  #   menu = "navbar"
  # or by specifying menu entries in a similar way to the sidebar menu above.
  #custom_navbar = true

  # show sharing icons on pages/posts (default: true)
  #sharingicons = true

  # Display post summaries instead of content in list templates (default: true)
  #truncate = true

  # Disable the use of sub-resource integrity on CSS/JS assets (default: false)
  # Useful if you're using a CDN or other host where you can't control cache headers
  #disable_sri = false

  [params.sidebar]
    # Optional about block for sidebar (can be Markdown)
    about = "Dave Russell is a software developer, exploring and enjoying the [go](https://golang.org) language and community"

    # How many posts to show on the sidebar (Default: 5)
    #num_recent_posts = 2

  [params.social]
    # Optional, used for attribution in Twitter cards (ideally not a person
    # for example: nytimes, flickr, NatGeo, etc).
    # See: https://dev.twitter.com/cards/types/summary-large-image
    twitter = "forfuncsake"
